### ISSUE TITLE
Failed To Download All News On Refresh

### ISSUE THREAD

**Issue by rajasone** [ICT4Dat/ict4dat-news-android#156]
There is a problem while downloading/updating news, This [www.ict4d.at/81.19.159.57]( www.ict4d.at/81.19.159.57) is not responding to a request, Exception is bellow 
```
2019-03-10 01:17:51.546 12325-12369/at.ict4d.ict4dnews D/OkHttp: <-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to www.ict4d.at/81.19.159.57 (port 80) from /192.168.43.239 (port 48749) after 30000ms
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server: Error in downloading an author from a self-hosted Wordpress blog
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server: java.net.SocketTimeoutException: failed to connect to www.ict4d.at/81.19.159.57 (port 80) from /192.168.43.239 (port 48749) after 30000ms
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at libcore.io.IoBridge.connect(IoBridge.java:130)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at java.net.Socket.connect(Socket.java:616)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-03-10 01:17:51.556 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at okhttp3.RealCall.execute(RealCall.java:77)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server.handleSelfHostedWPBlogList(Server.kt:146)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server.access$handleSelfHostedWPBlogList(Server.kt:31)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:72)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:31)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:112)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Observable.subscribe(Observable.java:12090)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Observable.subscribe(Observable.java:12090)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3438)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3438)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3438)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2019-03-10 01:17:51.557 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-03-10 01:17:51.558 12325-12369/at.ict4d.ict4dnews E/Server:     at java.lang.Thread.run(Thread.java:764)

```

**Comment by rajasone** [comment]
@spipau please find current exception down here
```
2019-03-24 23:55:47.978 3723-3723/at.ict4d.ict4dnews D/ICT4DNewsFragment$onCreateView: list in fragment: 86 ---- 
2019-03-24 23:55:47.983 3723-3723/at.ict4d.ict4dnews I/chatty: uid=10254(at.ict4d.ict4dnews) identical 3 lines
2019-03-24 23:55:47.984 3723-3723/at.ict4d.ict4dnews D/ICT4DNewsFragment$onCreateView: list in fragment: 86 ---- 
2019-03-24 23:55:48.326 3723-3775/at.ict4d.ict4dnews D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "will.be.overritten.com": No address associated with hostname
2019-03-24 23:55:48.344 3723-3775/at.ict4d.ict4dnews E/Server: Error in downloading an author from a self-hosted Wordpress blog
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server: java.net.UnknownHostException: Unable to resolve host "will.be.overritten.com": No address associated with hostname
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at java.net.InetAddress.getAllByName(InetAddress.java:787)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.Dns$-CC.lambda$static$0(Dns.java:39)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.-$$Lambda$Dns$mTkNcZf2K4euny3_jks6Cac6Az0.lookup(Unknown Source:0)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:221)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at okhttp3.RealCall.execute(RealCall.java:93)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
2019-03-24 23:55:48.345 3723-3775/at.ict4d.ict4dnews E/Server:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server.handleSelfHostedWPBlogList(Server.kt:146)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server.access$handleSelfHostedWPBlogList(Server.kt:31)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:72)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:31)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:112)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Observable.subscribe(Observable.java:12268)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Observable.subscribe(Observable.java:12268)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3603)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3603)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Single.subscribe(Single.java:3603)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server:     at java.lang.Thread.run(Thread.java:764)
2019-03-24 23:55:48.346 3723-3775/at.ict4d.ict4dnews E/Server: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
2019-03-24 23:55:48.347 3723-3775/at.ict4d.ict4dnews E/Server:     at libcore.io.Linux.android_getaddrinfo(Native Method)
2019-03-24 23:55:48.347 3723-3775/at.ict4d.ict4dnews E/Server:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
2019-03-24 23:55:48.347 3723-3775/at.ict4d.ict4dnews E/Server:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
2019-03-24 23:55:48.347 3723-3775/at.ict4d.ict4dnews E/Server: 	... 56 more
2019-03-24 23:55:48.359 3723-3992/at.ict4d.ict4dnews E/Server$loadAllNewsFromAllActiveBlogs: Error in downloading news from all active posts
    java.net.UnknownHostException: Unable to resolve host "will.be.overritten.com": No address associated with hostname
        at at.ict4d.ict4dnews.server.Server.handleSelfHostedWPBlogList(Server.kt:153)
        at at.ict4d.ict4dnews.server.Server.access$handleSelfHostedWPBlogList(Server.kt:31)
        at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:72)
        at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:31)
        at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:112)
        at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-03-24 23:55:48.379 3723-3723/at.ict4d.ict4dnews E/RXErrorEventBusLifecycleObserver$registerEventBus: java.net.UnknownHostException: Unable to resolve host "will.be.overritten.com": No address associated with hostname
        at at.ict4d.ict4dnews.server.Server.handleSelfHostedWPBlogList(Server.kt:153)
        at at.ict4d.ict4dnews.server.Server.access$handleSelfHostedWPBlogList(Server.kt:31)
        at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:72)
        at at.ict4d.ict4dnews.server.Server$loadAllNewsFromAllActiveBlogs$2.apply(Server.kt:31)
        at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:112)
        at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by rajasone** [comment]
@spipau it seems like a same blog (ict4d.at) the difference is only exception, in first exception it is about TimeOut and in second exception it is invalid url
