### ISSUE TITLE
Failed To Download News When App Starts For First Time

### ISSUE THREAD

**Issue by rajasone** [ICT4Dat/ict4dat-news-android#171]
To reproduce this exception **uninstall the app and install app again**, First time I got this exception

```
2019-04-03 22:59:55.785 30626-30655/at.ict4d.ict4dnews D/OkHttp: <-- END HTTP (268811-byte body)
2019-04-03 22:59:55.883 30626-30655/at.ict4d.ict4dnews D/OkHttp: --> GET https://matthaikin.com/feed/
2019-04-03 22:59:55.883 30626-30655/at.ict4d.ict4dnews D/OkHttp: --> END GET
2019-04-03 22:59:55.885 30626-30632/at.ict4d.ict4dnews I/zygote64: Do full code cache collection, code=496KB, data=314KB
2019-04-03 22:59:55.889 30626-30632/at.ict4d.ict4dnews I/zygote64: After code cache collection, code=342KB, data=200KB
2019-04-03 23:00:12.665 30626-30655/at.ict4d.ict4dnews D/OkHttp: <-- HTTP FAILED: okhttp3.internal.http2.ConnectionShutdownException
2019-04-03 23:00:12.675 30626-30763/at.ict4d.ict4dnews E/Server$loadAllNewsFromAllActiveBlogs: Error in downloading news from all active posts
    okhttp3.internal.http2.ConnectionShutdownException
        at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:242)
        at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:225)
        at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-04-03 23:00:12.699 30626-30626/at.ict4d.ict4dnews E/RXErrorEventBusLifecycleObserver$registerEventBus: okhttp3.internal.http2.ConnectionShutdownException
        at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:242)
        at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:225)
        at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

I uninstall the app and install it again I got this exception

```
2019-04-03 23:05:44.818 30960-30989/at.ict4d.ict4dnews D/OkHttp: --> GET https://www.panoplydigital.com/blog?format=rss
2019-04-03 23:05:44.818 30960-30989/at.ict4d.ict4dnews D/OkHttp: --> END GET
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: <-- 200 https://www.panoplydigital.com/blog?format=rss (8616ms)
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: date: Wed, 03 Apr 2019 18:05:46 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-servedby: web044
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: strict-transport-security: max-age=0
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: set-cookie: ss_cid=3f57a868-8945-4edc-8397-952e6593f01d;Path=/;Expires=Fri, 02-Apr-2021 18:05:47 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: set-cookie: ss_cvisit=1554314747110;Path=/;Expires=Wed, 03-Apr-2019 18:35:47 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: set-cookie: ss_cpvisit=1554314747110;Path=/;Expires=Fri, 02-Apr-2021 18:05:47 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: accept-ranges: bytes
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: content-type: application/rss+xml; charset=UTF-8
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-pc-date: Wed, 03 Apr 2019 16:07:11 GMT
2019-04-03 23:05:53.436 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-pc-host: 10.122.10.250
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: etag: W/"0eeaa14f948c9b21465e617e295356e4"
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-pc-key: psIfLUEnSSN8kUpZJc-kdRdqQME-michael-gallagher-5j67
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-pc-hit: true
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: content-length: 806373
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: server: envoy
2019-04-03 23:05:53.437 30960-30989/at.ict4d.ict4dnews D/OkHttp: age: 0
2019-04-03 23:05:53.438 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-varnish: varnish-web005
2019-04-03 23:05:53.438 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-contextid: VpPQzx3h/3Cn7yevU
2019-04-03 23:05:53.438 30960-30989/at.ict4d.ict4dnews D/OkHttp: x-via: 1.1 echo030
2019-04-03 23:06:58.076 30960-31224/at.ict4d.ict4dnews E/Server$loadAllNewsFromAllActiveBlogs: Error in downloading news from all active posts
    okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:419)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:217)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:175)
        at okio.RealBufferedSource.request(RealBufferedSource.java:72)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:249)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-04-03 23:06:58.099 30960-30960/at.ict4d.ict4dnews E/RXErrorEventBusLifecycleObserver$registerEventBus: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:419)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:217)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:175)
        at okio.RealBufferedSource.request(RealBufferedSource.java:72)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:249)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleZipIterable.subscribeActual(SingleZipIterable.java:78)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by spipau** [comment]
Hi, I just deleted and installed the current version and everything worked? @rajasone what happend in detail?
1. Did the app crash?
1. Were there news in the list available, only `panoplydigital` or `https://matthaikin.com/feed/` were missing?
1. Were there no items in the list?
